name: test

on:
 push:
  branches: ['main']


jobs:
  license-checking:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: 'Install license-finder'
      run: |
        echo "Installing license_finder"
        sudo apt install ruby ruby-dev
        sudo gem install license_finder

    - name: Set up JDK 17 and Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: maven load dependency
      run: |
        mvn dependency:resolve
        
    - name: check license scan
      run: |
        license_finder --project-path=.

    # - name: check license scan
    #   run: |
    #     if license_finder --project-path=. --decisions-file=license_decisions.yml | grep -q "Dependencies that need approval"; then
    #       echo "There are dependency's that need to approval"
    #       exit 1
    #     else
    #      echo "All dependencies are approved"
    #     fi