name: test

on:
 push:
  branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test branch name
      run: | 
        BRANCH_NAME="${{ github.ref_name }}"
        REPO_NAME="${{ github.repository }}"
        echo $BRANCH_NAME
        echo $REPO_NAME