# name: test

# on:
#   push: 
#     branches: ['main']

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     outputs:
#       image_tag: ${{ steps.vars.outputs.image_tag }}
#     steps:
      # - name: Set Image Tags
      #   id: vars
      #   run: |
      #     IMAGE_TAG=${{ github.ref_name }}-$(echo $GITHUB_SHA | head -c 8)
      #     echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      #     echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
      
#       - name: print image tag
#         run: |
#            echo "${{ steps.vars.outputs.image_tag }}"