name: test docker login

on:
  push:
   branches: ['main']

permissions:
 id-tokens: write

jobs:
  docker-login:
   runs-on: ubuntu-latest

   steps:
    - name: configure aws creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
       role-to-assume: ${{ secrets.AWS_IAM_ROLE_ATHENTICATION }}
       aws-region: 'ap-south-1'

    - name: login to ecr
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v2
  